# Generated by Django 4.1.3 on 2022-11-27 17:15

import discover_art.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), discover_art.core.validators.validate_only_letters], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), discover_art.core.validators.validate_only_letters], verbose_name='Last Name')),
                ('message', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
            },
        ),
    ]
