# Generated by Django 4.1.3 on 2022-11-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='used_materials',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
