# Generated by Django 4.1.3 on 2022-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_products', '0002_product_size_product_used_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='used_materials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
